services:
  nginx:
    image: nginx:latest
    container_name: private_services_nginx
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8088:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/etc/nginx/html:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      backend:
        condition: service_healthy
  backend:
    image: littleorange666/private_services:0.0.15
    environment:
      - TZ=Asia/Taipei
      - DOCKER_HOST=unix:///app/docker.sock
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./data/nginx:/app/nginx:rw
      - ./data/backend:/app/data:rw
      - ./templates:/app/templates:ro
      - /var/run/docker.sock:/app/docker.sock:rw
    restart: on-failure
    ports:
      - "8089:8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import http.client; c=http.client.HTTPConnection('localhost', 8000); c.request('GET', '/health_check'); r=c.getresponse(); exit(0) if r.status < 400 else exit(1)"]
      interval: 10s
      start_period: 10s
      timeout: 3s
      retries: 5